# Режим разработки
version: "3.9"

services:
  flask-app:
    build: .
    container_name: flask-app-dev
    ports:
      - "5000:5000"

    # Монтируем весь проект — удобно для разработки
    volumes:
      - .:/app
      - ./app/data:/app/app/data

    env_file:
      - .env

    environment:
      FLASK_ENV: development

    restart: unless-stopped
